// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwQ3uhmZTutlByErElIk-Jd4NoYjFRueY',
    appId: '1:898779811017:web:9619442fc8d584ece65118',
    messagingSenderId: '898779811017',
    projectId: 'focusly-76449',
    authDomain: 'focusly-76449.firebaseapp.com',
    storageBucket: 'focusly-76449.firebasestorage.app',
    measurementId: 'G-LCJ9CYW2FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB901F-dVenV4KD13ORIGv7HOk2l4N_6jU',
    appId: '1:898779811017:android:d2e595ea873882e1e65118',
    messagingSenderId: '898779811017',
    projectId: 'focusly-76449',
    storageBucket: 'focusly-76449.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACbGxZu12Qd-JaD0Bzts0v2LwuJDjmo38',
    appId: '1:898779811017:ios:bfbb92004b705b9be65118',
    messagingSenderId: '898779811017',
    projectId: 'focusly-76449',
    storageBucket: 'focusly-76449.firebasestorage.app',
    androidClientId: '898779811017-vlubqiecjqqpd9ufkp395ch7lein6m54.apps.googleusercontent.com',
    iosClientId: '898779811017-6ep6do9ittl44ids3o8g0riuf3q5p0pb.apps.googleusercontent.com',
    iosBundleId: 'com.esof.focusly',
  );

}