name: focusly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  material_symbols_icons: ^4.2810.1
  audioplayers: ^6.4.0
  flutter_local_notifications: ^19.0.0
  permission_handler: ^11.4.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.2
  provider: ^6.1.3
  firebase_database: ^11.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  provider: ^6.1.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/sound.wav

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"